# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: CopyFiles@2
  displayName: Copy provisioning scripts
  inputs:
    SourceFolder: azurestaticwebsite\AzureStaticWeb.Provisioning
    TargetFolder: '$(build.artifactstagingdirectory)/iac'

- task: CopyFiles@2
  displayName: Copy content
  inputs:
    SourceFolder: content
    TargetFolder: '$(build.artifactstagingdirectory)/content'

- task: PublishBuildArtifacts@1
  displayName: Infrastructure provisioning
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/iac'
    ArtifactName: iac

- task: PublishBuildArtifacts@1
  displayName: Site
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/website'